# Woodpecker CI configuration
# Fetches centralized build script from daemonless/daemonless

steps:
  - name: build-latest
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        mkdir -p scripts
        fetch -qo scripts/build.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-v1.1.1/scripts/build.sh"
        chmod +x scripts/build.sh
        ./scripts/build.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/woodpecker \
          --tag latest \
          --tag-version \
          --skip-wip \
          --login --push

when:
  - event: push
    branch: main
    path:
      exclude: [ "*.md", "docs/**", "LICENSE", ".gitignore" ]
  - event: manual
