# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

# Woodpecker CI (Server & Agent) for FreeBSD
# Multi-stage build

# Stage 1: Build the frontend (Web UI)
ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS frontend-builder
RUN pkg update && pkg install -y node22 npm-node22 git ca_root_nss
RUN npm install -g pnpm
ARG VERSION=latest
RUN if [ "$VERSION" = "latest" ]; then \
      VERSION=$(fetch -qo - https://api.github.com/repos/woodpecker-ci/woodpecker/releases/latest | jq -r .tag_name); \
    fi && \
    echo "$VERSION" > /version.txt && \
    git clone --depth 1 --branch ${VERSION} https://github.com/woodpecker-ci/woodpecker.git /src
WORKDIR /src/web
RUN pnpm install --frozen-lockfile && pnpm build

# Stage 2: Build the backend (Server, Agent, CLI, plugin-git)
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS backend-builder
RUN pkg update && pkg install -y go126 git ca_root_nss sqlite3 \
    FreeBSD-clang FreeBSD-clang-dev FreeBSD-clibs-dev FreeBSD-runtime-dev \
    FreeBSD-audit-dev
RUN ln -sf /usr/bin/clang /usr/bin/cc
COPY --from=frontend-builder /src /src
COPY --from=frontend-builder /version.txt /version.txt
WORKDIR /src
# Enable CGO for sqlite3 support
ENV CGO_ENABLED=1
ENV GOPROXY=direct
ENV GONOSUMDB=*
RUN export VERSION=$(cat /version.txt) && \
    /usr/local/bin/go126 build -tags 'sqlite_unlock_notify' -ldflags "-X go.woodpecker-ci.org/woodpecker/v3/version.Version=${VERSION}" -o /bin/woodpecker-server ./cmd/server && \
    /usr/local/bin/go126 build -ldflags "-X go.woodpecker-ci.org/woodpecker/v3/version.Version=${VERSION}" -o /bin/woodpecker-agent ./cmd/agent && \
    /usr/local/bin/go126 build -ldflags "-X go.woodpecker-ci.org/woodpecker/v3/version.Version=${VERSION}" -o /bin/woodpecker-cli ./cmd/cli
# Build plugin-git for FreeBSD
RUN git clone --depth 1 https://github.com/woodpecker-ci/plugin-git.git /plugin-git && \
    cd /plugin-git && \
    /usr/local/bin/go126 build -o /bin/plugin-git

# Stage 3: Final Runtime
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="ca_root_nss git sqlite3 podman gsed gawk gnugrep git-lfs"
ARG UPSTREAM_URL="https://api.github.com/repos/woodpecker-ci/woodpecker/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:8000/healthz"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Woodpecker CI" \
      org.opencontainers.image.description="Lightweight CI/CD pipeline server with a built-in agent — integrates with Gitea, GitHub, and GitLab for automated builds and deployments." \
      org.opencontainers.image.source="https://github.com/daemonless/woodpecker" \
      org.opencontainers.image.url="https://woodpecker-ci.org/" \
      org.opencontainers.image.documentation="https://woodpecker-ci.org/docs/intro" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Infrastructure" \
      io.daemonless.port="8000" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Runtime dependencies
RUN pkg update && pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Woodpecker needs a writable HOME for some operations
RUN pw usermod bsd -d /config
ENV HOME=/config

COPY --from=backend-builder /bin/woodpecker-server /usr/local/bin/
COPY --from=backend-builder /bin/woodpecker-agent /usr/local/bin/
COPY --from=backend-builder /bin/woodpecker-cli /usr/local/bin/
COPY --from=backend-builder /bin/plugin-git /usr/local/bin/
COPY --from=frontend-builder /version.txt /version.txt

RUN chmod 755 /usr/local/bin/woodpecker-server /usr/local/bin/woodpecker-agent /usr/local/bin/woodpecker-cli /usr/local/bin/plugin-git && \
    mkdir -p /app && cp /version.txt /app/version && rm /version.txt

# Configure Woodpecker to use local plugin-git
ENV WOODPECKER_BACKEND_LOCAL_CLONE=/usr/local/bin/plugin-git

COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 8000 9000

# --- Volumes (Injected by Generator) ---
VOLUME /config